name: Run Tests and Linting

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    name: Run ESLint and Jest Tests
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint  # Assuming that "npm run lint" runs ESLint
      - run: npm run test  # "npm run test" to run Jest tests
